# Generated by Django 5.2.7 on 2025-11-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HocVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('goi_tap', models.CharField(max_length=100)),
                ('ngay_het_han', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BuoiTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tap', models.DateField()),
                ('bai_tap', models.CharField(max_length=100)),
                ('trang_thai', models.CharField(choices=[('Đã hoàn thành', 'Đã hoàn thành'), ('Chưa tập', 'Chưa tập')], default='Chưa tập', max_length=50)),
                ('hoc_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quanlylichtap.hocvien')),
            ],
        ),
        migrations.CreateModel(
            name='NhanXet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('ngay_nhan_xet', models.DateTimeField(auto_now_add=True)),
                ('buoi_tap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Quanlylichtap.buoitap')),
            ],
        ),
    ]
