# Generated by Django 5.2.8 on 2025-11-12 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlylichtap', '0003_notification'),
        ('taikhoan', '0003_huanluyenvien_khachhang_nhanvien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buoitap',
            name='hoc_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taikhoan.khachhang'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='nguoi_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taikhoan.khachhang'),
        ),
        migrations.DeleteModel(
            name='HocVien',
        ),
    ]
