# Generated by Django 5.2.8 on 2025-11-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlylichtap', '0004_alter_buoitap_hoc_vien_alter_thongbao_nguoi_nhan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buoitap',
            name='cam_nhan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buoitap',
            name='muc_ta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buoitap',
            name='so_hiep',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
