# Generated by Django 5.2.8 on 2025-11-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlylichtap', '0005_buoitap_cam_nhan_buoitap_muc_ta_buoitap_so_hiep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buoitap',
            name='trang_thai',
            field=models.CharField(choices=[('Đã hoàn thành', 'Đã hoàn thành'), ('Chưa hoàn thành', 'Chưa hoàn thành')], default='Chưa hoàn thành', max_length=50),
        ),
    ]
