# Generated by Django 5.2.8 on 2025-11-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlylichtap', '0006_alter_buoitap_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongbao',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
