# Generated by Django 5.2.8 on 2025-11-30 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlylichtap', '0007_thongbao_is_read_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HinhAnhCamNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh', models.ImageField(upload_to='cam_nhan/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('buoi_tap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_anh_cam_nhan', to='Quanlylichtap.buoitap')),
            ],
        ),
    ]
