# Generated by Django 5.2.8 on 2025-11-30 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlylichtap', '0008_hinhanhcamnhan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HinhAnhNhanXet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh', models.ImageField(upload_to='nhan_xet_hlv/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('nhan_xet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anh', to='Quanlylichtap.nhanxet')),
            ],
        ),
    ]
