# Generated by Django 5.2.6 on 2025-11-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quanlylichtap', '0009_hinhanhnhanxet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thongbao',
            options={'ordering': ['-thoi_gian'], 'verbose_name': 'Thông báo', 'verbose_name_plural': 'Thông báo'},
        ),
    ]
