# Generated by Django 5.2.5 on 2025-11-10 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Khách hàng'), ('trainer', 'Huấn luyện viên'), ('staff', 'Nhân viên')], default='customer', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Họ và tên')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ảnh đại diện (đường dẫn)')),
                ('goal', models.CharField(blank=True, max_length=255, verbose_name='Mục tiêu tập luyện')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiều cao (cm)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cân nặng (kg)')),
                ('certificates', models.CharField(blank=True, max_length=255, verbose_name='Chứng chỉ')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kinh nghiệm (năm)')),
                ('bio', models.CharField(blank=True, max_length=255, verbose_name='Giới thiệu')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Phòng ban')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
