# Generated by Django 5.2.8 on 2025-11-12 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taikhoan', '0002_profile_unique_profile_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuanLuyenVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuyen_mon', models.CharField(blank=True, max_length=255)),
                ('nam_kinh_nghiem', models.PositiveIntegerField(blank=True, null=True)),
                ('gioi_thieu', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muc_tieu', models.CharField(blank=True, max_length=255)),
                ('chieu_cao_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('can_nang_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('goi_tap', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phong_ban', models.CharField(blank=True, max_length=100)),
                ('ghi_chu', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='profile',
            name='unique_profile_per_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='note',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='profile',
            name='anh_dai_dien',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='huanluyenvien',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='huan_luyen_vien', to='taikhoan.profile'),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='khach_hang', to='taikhoan.profile'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_vien', to='taikhoan.profile'),
        ),
    ]
