# Generated by Django 5.2.8 on 2025-11-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taikhoan', '0003_huanluyenvien_khachhang_nhanvien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='ngay_het_han',
            field=models.DateField(blank=True, null=True),
        ),
    ]
