# Generated by Django 5.2.8 on 2025-11-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taikhoan', '0004_khachhang_ngay_het_han'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
