# Generated by Django 5.2.8 on 2025-11-20 22:24

import django.db.models.deletion
import taikhoan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taikhoan', '0005_alter_profile_anh_dai_dien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='khoa_boi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='da_khoa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='khoa_luc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ly_do_khoa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to=taikhoan.models.profile_avatar_path),
        ),
    ]
