# Generated by Django 6.0 on 2025-12-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taikhoan', '0006_profile_khoa_boi_profile_khoa_luc_profile_ly_do_khoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='huan_luyen_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoc_vien_quan_ly', to='taikhoan.huanluyenvien'),
        ),
    ]
