# Generated by Django 5.2.6 on 2025-12-06 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraLoiKhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung_tra_loi', models.TextField(verbose_name='Nội dung trả lời')),
                ('ngay_tra_loi', models.DateTimeField(auto_now_add=True)),
                ('nguoi_tra_loi', models.CharField(max_length=100)),
                ('phan_hoi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tra_loi_khachhang', to='hotro.phanhoi')),
            ],
        ),
    ]
