# Generated by Django 5.2.6 on 2025-12-06 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhanHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('Khiếu nại', 'Khiếu nại'), ('Góp ý', 'Góp ý'), ('Thắc mắc', 'Thắc mắc')], max_length=50)),
                ('noi_dung', models.TextField()),
                ('trang_thai', models.CharField(default='Chưa xử lý', max_length=20)),
                ('tra_loi', models.TextField(blank=True, null=True)),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnhPhanHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh', models.ImageField(blank=True, null=True, upload_to='phanhoi/')),
                ('phan_hoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_anh', to='hotro.phanhoi')),
            ],
        ),
    ]
