# Generated by Django 5.2.6 on 2025-11-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phanhoi',
            name='loai',
            field=models.CharField(choices=[('Khieu nai', 'Khiếu nại'), ('Gop y', 'Góp ý'), ('Thắc mắc', 'Thắc mắc')], max_length=50),
        ),
    ]
