# Generated by Django 5.2.6 on 2025-12-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anhphanhoi',
            name='is_temp_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
