# Generated by Django 5.2.6 on 2025-12-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotro', '0002_anhphanhoi_is_temp_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anhphanhoi',
            name='is_temp_deleted',
        ),
    ]
