# Generated by Django 5.2.6 on 2025-11-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotro', '0003_alter_phanhoi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phanhoi',
            name='ngay_gui',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
