# Generated by Django 5.2.6 on 2025-11-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotro', '0004_alter_phanhoi_ngay_gui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phanhoi',
            name='loai',
            field=models.CharField(choices=[('Khiếu nại', 'Khiếu nại'), ('Góp ý', 'Góp ý'), ('Thắc mắc', 'Thắc mắc')], max_length=50),
        ),
    ]
