# Generated by Django 5.2.6 on 2025-11-13 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotro', '0006_alter_phanhoi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phanhoi',
            name='ngay_gui',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
