# Generated by Django 5.2.6 on 2025-11-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotro', '0007_alter_phanhoi_ngay_gui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phanhoi',
            name='ngay_gui',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
