# Generated by Django 5.2.6 on 2025-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotro', '0008_alter_phanhoi_ngay_gui'),
    ]

    operations = [
        migrations.AddField(
            model_name='phanhoi',
            name='anh',
            field=models.ImageField(blank=True, null=True, upload_to='phanhoi/'),
        ),
    ]
