# Generated by Django 6.0 on 2025-12-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotro', '0002_anhphanhoi_is_temp_deleted'),
        ('hotro', '0009_phanhoi_anh'),
    ]

    operations = [
    ]
