# Generated by Django 6.0 on 2025-12-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotro', '0010_merge_20251206_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phanhoi',
            name='anh',
        ),
    ]
