# Generated by Django 6.0 on 2025-12-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotro', '0003_remove_anhphanhoi_is_temp_deleted'),
        ('hotro', '0011_remove_phanhoi_anh'),
    ]

    operations = [
    ]
