# Generated by Django 5.2.6 on 2025-11-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danh_gia_chung', models.IntegerField(default=0)),
                ('thai_do_phuc_vu', models.IntegerField(default=0)),
                ('chat_luong_dich_vu', models.IntegerField(default=0)),
                ('nhan_xet', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
