# Generated by Django 5.2.6 on 2025-11-09 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danhgia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia',
            name='ngay_tao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
