# Generated by Django 5.2.8 on 2025-11-12 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danhgia', '0002_alter_danhgia_ngay_tao'),
        ('taikhoan', '0003_huanluyenvien_khachhang_nhanvien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='khach_hang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taikhoan.khachhang'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danhgia',
            name='nguoi_tao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taikhoan.profile'),
        ),
    ]
