# Generated by Django 5.2.8 on 2025-11-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danhgia', '0003_danhgia_khach_hang_danhgia_nguoi_tao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
