# Generated by Django 5.2.6 on 2025-11-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danhgia', '0004_alter_danhgia_ngay_tao'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='anh_minh_chung',
            field=models.ImageField(blank=True, null=True, upload_to='danhgia/'),
        ),
    ]
