# Generated by Django 5.2.6 on 2025-12-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danhgia', '0006_danhgia_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhgia',
            name='anh_minh_chung',
        ),
        migrations.CreateModel(
            name='DanhGiaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='danhgia/')),
                ('danh_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='danhgia.danhgia')),
            ],
        ),
    ]
